### ISSUE TITLE
GIFs not working, JAVA

### ISSUE THREAD

**Issue by Saltay2822** [LOOHP/ImageFrame#13]
I'm not entirely sure if its just me being stupid but gifs just don't work.

Every time me or anyone on my server tries to add a gif there able to create the map but once they place it it is just stuck on the first frame of the gif and doesn't animate. we have tried gifs from all different sources and none of them have worked. we even tried looking into the code but none of us understand it so it wasn't any help. I am also on java edition

**Comment by LOOHP** [comment]
Did you give permission to create animated image maps?

**Comment by Saltay2822** [comment]
I solved the issue I realize it was a problem with the install that just required a simple reinstall im sorry for any inconveniences.
