### ISSUE TITLE
Limit to gifs?

### ISSUE THREAD

**Issue by Saltay2822** [LOOHP/ImageFrame#14]
yo is there a limit to the amount of gifs one can have cause i got 9 working ones but every other one that i added is stuck on the first frame. other people are able to add there own gifs that work but after i placed 9 i cant seem to place any more working ones. 
no one else on my server has placed more then like 4 gifs im the only one with 9 gifs and the rest that i placed just dont work

**Comment by LOOHP** [comment]
It's probably another problem. There might be a problem with the last GIF you tried to import.
