### ISSUE TITLE
where does the pixel art go?

### ISSUE THREAD

**Issue by AlessandroLatto** [LOOHP/ImageFrame#17]
i'm sorry, but where does the pixel art go? because it's obviously a pixel art

**Comment by LOOHP** [comment]
I'm sorry, I'm not sure what issue you are facing regarding IF.

**Comment by AlessandroLatto** [comment]
basically, i think that this plugin makes pixel arts for the images and i am questioning where do the pixel art go.

**Comment by AlessandroLatto** [comment]
sorry, clicked "close with comment"

**Comment by LOOHP** [comment]
IF allows you to load images from the internet onto maps. It is not a pixel art plugin, although you could import pixel art as images.

**Comment by AlessandroLatto** [comment]
so no pixel art is placed on the world ?

**Comment by LOOHP** [comment]
Images are loaded into maps, you can then put the map onto item frames.

**Comment by AlessandroLatto** [comment]
thank you, i was scared that i was gonna find 2000 pixel arts from my 20 players. thank you
