### ISSUE TITLE
[Feature Request] Command Block Compatibility

### ISSUE THREAD

**Issue by GhostIsBeHere** [LOOHP/ImageFrame#23]
I would like the ability to swap maps out using command blocks. Probably could be done by adding a command that would work like the "get" command with a built-in selection.
Example:
`/imageframe place <name> <x1> <y1> <z1> <x2> <y2> <z2>`
Also, I would like to be able to run `/imageframe refresh [name]` from command blocks, kind of like with #16 
Thank you! I absolutly love your plugin <3

**Comment by LOOHP** [comment]
The "refresh" part of this request is now available since 425c9bc
