### ISSUE TITLE
[Feature request] Prevent putting image frame maps into cartography table

### ISSUE THREAD

**Issue by RhythmicSys** [LOOHP/ImageFrame#3]
When attempting to change the zoom level using a cartography table with an image map it makes it blank: 

![image](https://user-images.githubusercontent.com/45906780/201203708-1aaf6bf8-0350-4796-92af-4873c05042a5.png)

When trying to lock an image map, it makes it blank:

![image](https://user-images.githubusercontent.com/45906780/201203748-594f38c7-bb27-4293-a595-73e64a8ae525.png)

It would be helpful if this were prevented from happening c:

**Comment by LOOHP** [comment]
Please give the latest build a try!
https://ci.loohpjames.com/view/Spigot-Plugins/job/ImageFrame/

**Comment by RhythmicSys** [comment]
Works awesome! Thanks so much :D
