### ISSUE TITLE
[Feature Request] Turn deleted maps into empty maps

### ISSUE THREAD

**Issue by RhythmicSys** [LOOHP/ImageFrame#4]
Currently when deleting a map, it leaves a filled, yet empty map

![image](https://user-images.githubusercontent.com/45906780/201204396-6223bcc2-28fc-4492-95b6-9ac07d310871.png)

it would be cool if it returned an empty map item so that it could be reused

**Comment by LOOHP** [comment]
There is a slight problem with this, what about other maps in a random chest or an offline player?

**Comment by LOOHP** [comment]
Please give the latest build a try!
https://ci.loohpjames.com/view/Spigot-Plugins/job/ImageFrame/

**Comment by RhythmicSys** [comment]
Works great :3 thanks!
