### ISSUE TITLE
Multiword incompatibility issue

### ISSUE THREAD

**Issue by dnchshrp** [LOOHP/ImageFrame#53]
Hi! I love this plugin, it's simple and very useful, but I found a big issue.

Imagine a scenario: There's a multiworld server(thet uses MultiverseCore), that has a lobby, a survival world and few minigames. There's a GIF, that displays something, located in the lobby. When a player joins, he looks around, sees the GIF, and goes to the survival world or to a minigame. Then, he gets bored, goes to the lobby, and sees - the GIF now doesn't display at all! The GIF starts displaying again only when he rejoins the server. You get the point - if a player enters a world with a GIF, goes somewhere else, and then returns to the world with a GIF - it stops working until the player rejoins. I hope this will be fixed, because it's a bit annoying. 

Thank you in advance!

**Comment by LOOHP** [comment]
Does this happen if you go through nether portals as well?

**Comment by dnchshrp** [comment]
Yes, the same thing happens, I visit the nether, the GIF works, I go back to overworld, go again to nether and the GIF doesn't work

**Comment by dnchshrp** [comment]
I just updated the plugin to 1.7.8 and things got worse. Now sometimes the GIF disappears entirely and doesn't show even when the player rejoins, after going between some worlds the gif starts playing but only like 2-3 frames of the animations are shown.

**Comment by LOOHP** [comment]
Are you using ImageFrame 1.7.8.2? I could not reproduce your issue on the latest dev build.

**Comment by dnchshrp** [comment]
That's a bit strange. By 1.7.8 I mean the latest version of the plugin on spigotmc.org, the version I was using when I originally submitted the issue was 1.7.7. Maybe the issue could happen because my server is running 1.16.5? I can make a test server with the demonstration of this issue and send it to you

**Comment by LOOHP** [comment]
Can you try with the latest build on https://ci.loohpjames.com?

**Comment by dnchshrp** [comment]
Here's a test server that runs Paper 1.16.5 where I reproduced the issue:
https://drive.google.com/file/d/1tJM4jACAqkmal1co4YZKb0CFtUtMDTL-/view?usp=sharing

I tested three different plugin versions there:
- 1.7.7: The GIFs display correctly when I enter the world first time and stop working when I go to another world and then return back
- 1.7.8.2: The GIFs don't display when I enter the world first time and only start working when I go to another world and then return back, but only a few frames are shown which makes them look laggy
- latest bulid from ci.loohpjames.com: didn't encounter any minor or major differencies from 1.7.8.2

**Comment by LOOHP** [comment]
Thanks for the info, I couldn't reproduce this issue on build #102 anymore. Please give it a try and see if it is for you as well.

**Comment by dnchshrp** [comment]
I tried using build #102 from Jenkins and the behaviour is the same as in 1.7.7 :(

**Comment by LOOHP** [comment]
I've tested using nether portals, going back and forth. The gif continues to show on both sides.
