### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by w1th0utme** [LOOHP/ImageFrame#58]
Server version: 1.20.4
ImageFrame version: 1.7.8.2

```
Craft Scheduler Thread - 8607 - ImageFrame
  at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.lambda$buildAllItemFrameInfo$0(Lorg/bukkit/entity/ItemFrame;Lcom/google/common/collect/ImmutableMap$Builder;Ljava/util/concurrent/CompletableFuture;)V (AnimatedFakeMapManager.java:122)
  at com.loohp.imageframe.objectholders.AnimatedFakeMapManager$$Lambda+0x00007f04f3fd4000.run()V ()
  at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.buildAllItemFrameInfo(Ljava/util/Set;Z)Lcom/google/common/collect/ImmutableMap; (AnimatedFakeMapManager.java:130)
  at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.run()V (AnimatedFakeMapManager.java:155)
  at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run()V (CraftTask.java:100)
  at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run()V (CraftAsyncTask.java:57)
  at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run()V (ServerSchedulerReportingWrapper.java:22)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run()V (ThreadPoolExecutor.java:642)
  at java.lang.Thread.runWith(Ljava/lang/Object;Ljava/lang/Runnable;)V (Thread.java:1596)
  at java.lang.Thread.run()V (Thread.java:1583)
```
![image](https://github.com/LOOHP/ImageFrame/assets/137961937/76ced75a-bbd9-4ff2-8496-b13b78393a22)

![image](https://github.com/LOOHP/ImageFrame/assets/137961937/12092744-0c3c-4be6-88b7-707096218880)

![image](https://github.com/LOOHP/ImageFrame/assets/137961937/3d8a3c63-06b0-40d1-8545-a61f7918b5e5)

**Comment by LOOHP** [comment]
Which server implementation are you running?

**Comment by w1th0utme** [comment]
> Which server implementation are you running?

I can say pufferfish

**Comment by w1th0utme** [comment]
Do you have any ideas about that?

**Comment by ChanceSD** [comment]
I found a similar thing using v1.7.9.0, this is from a heap dump with 0 players online so there should be 0 CraftPlayer instances
![image](https://github.com/user-attachments/assets/2304ab35-b374-4b20-8956-c7e6cad2d5e3)
Seems like it comes from pendingKnownMapIds in com.loohp.imageframe.objectholders.AnimatedFakeMapManager, it's holding to Player instances even after they leave.

**Comment by Dreeam-qwq** [comment]
> I found a similar thing using v1.7.9.0, this is from a heap dump with 0 players online so there should be 0 CraftPlayer instances ![image](https://private-user-images.githubusercontent.com/5256215/355638517-2304ab35-b374-4b20-8956-c7e6cad2d5e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MDI5ODYsIm5iZiI6MTcyMzQwMjY4NiwicGF0aCI6Ii81MjU2MjE1LzM1NTYzODUxNy0yMzA0YWIzNS1iMzc0LTRiMjAtODk1Ni1jN2U2Y2FkMmQ1ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMTg1ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTMxYTdjZjI0MTRhNzExMzMyMzJmNjcyYjljZTM4MGY1NjM3NDEwYzNlYTE0MGM0YWIxNTllMWNmZjQ2NmEzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tBpJH_NZ8zngo4jFRHAJ3Gz7gGZ6WqAXN7U_JXzmbNk) Seems like it comes from pendingKnownMapIds in com.loohp.imageframe.objectholders.AnimatedFakeMapManager, it's holding to Player instances even after they leave.

Remove player object from pendingKnownMapIds map maybe can solve this?
https://github.com/LOOHP/ImageFrame/blob/e1fe6dc81ecf50c76562991400549844893b5013/common/src/main/java/com/loohp/imageframe/objectholders/AnimatedFakeMapManager.java#L338

btw, I think it's better to store player uuid as key instead of the entire player object.

**Comment by ChanceSD** [comment]
> > I found a similar thing using v1.7.9.0, this is from a heap dump with 0 players online so there should be 0 CraftPlayer instances ![image](https://private-user-images.githubusercontent.com/5256215/355638517-2304ab35-b374-4b20-8956-c7e6cad2d5e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MDI5ODYsIm5iZiI6MTcyMzQwMjY4NiwicGF0aCI6Ii81MjU2MjE1LzM1NTYzODUxNy0yMzA0YWIzNS1iMzc0LTRiMjAtODk1Ni1jN2U2Y2FkMmQ1ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMTg1ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTMxYTdjZjI0MTRhNzExMzMyMzJmNjcyYjljZTM4MGY1NjM3NDEwYzNlYTE0MGM0YWIxNTllMWNmZjQ2NmEzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tBpJH_NZ8zngo4jFRHAJ3Gz7gGZ6WqAXN7U_JXzmbNk) Seems like it comes from pendingKnownMapIds in com.loohp.imageframe.objectholders.AnimatedFakeMapManager, it's holding to Player instances even after they leave.
> 
> Under player quit event, remove player object from pendingKnownMapIds map maybe can solve this?
> 
> https://github.com/LOOHP/ImageFrame/blob/e1fe6dc81ecf50c76562991400549844893b5013/common/src/main/java/com/loohp/imageframe/objectholders/AnimatedFakeMapManager.java#L338
> 
> btw, I think it's better to store player uuid as key instead of the entire player object.

Yep, that's what I did on my fork, just removed it on quit event, not sure if there are any side effects but so far didn't notice any problem.
