### ISSUE TITLE
[Question] How to convert from ImageOnMaps?

### ISSUE THREAD

**Issue by LcyDev** [LOOHP/ImageFrame#6]
I tried using the command and it says it didn't find the folder
(On Windows)

**Comment by LOOHP** [comment]
Which version of ImageFrame are you using?

**Comment by LcyDev** [comment]
ImageFrame-1.6.2.0

**Comment by LcyDev** [comment]
I just found the [CI releases](https://ci.loohpjames.com/job/ImageFrame/)

I guess i need to use this?

**Comment by LOOHP** [comment]
Yes, try that and see

**Comment by LcyDev** [comment]
It worked, thanks!
