### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by Cyberillc** [LOOHP/ImageFrame#60]
<img width="473" alt="Screenshot 2024-06-17 at 9 46 42 AM" src="https://github.com/LOOHP/ImageFrame/assets/142674955/e21811b6-2c18-4ae2-8b44-c5d1fe9416f4">

**Comment by LOOHP** [comment]
If you mean the "s" in "maps", this is simply because I didn't make a separate message for singular. You could change it to something like "map(s)" in the config if you prefer that.
