### ISSUE TITLE
There is a problem with the plugin!

### ISSUE THREAD

**Issue by DimaSergeew** [LOOHP/ImageFrame#7]
For some reason, he doesn’t want to load any picture at all and always knocks out 1 and the same error on all my servers
MyServer: PurPur 1.19.3
VersionPluigns: (1.6.4)
Error: https://mclo.gs/2oGzf8E

**Comment by LOOHP** [comment]
Try adding the `-Djava.awt.headless=true` parameter in your server startup command.

**Comment by LOOHP** [comment]
Closed for inactivity.
