### ISSUE TITLE
Can Pictures become true colors？

### ISSUE THREAD

**Issue by OutlinedArc217** [LOOHP/ImageFrame#72]
This is an image I uploaded to Minecraft, and it has a big chromatic aberration...
（╯' - ')╯︵ ┻━┻ 

Can it be fixed?(/ω＼*)……… (/ω•＼*)?
![2024-08-19_19 55 10](https://github.com/user-attachments/assets/183d8909-3968-4c78-8052-c61e7ea5e05c)

**Comment by LOOHP** [comment]
Unfortunately no, as Minecraft maps are limited to only certain colors.

**Comment by OutlinedArc217** [comment]
> Unfortunately no, as Minecraft maps are limited to only certain colors.

wwwwwwwwwww,well,it's ok,thanks (｡í _ ì｡)
