### ISSUE TITLE
[Suggestion] Allow refreshing from console

### ISSUE THREAD

**Issue by Daelin-Campleman** [LOOHP/ImageFrame#78]
I'm not sure if there's a specific reason why this isn't allowed, but it would really help if images could be refreshed from the console. I'm using this plugin to display an image that's generated on a server and is updated on certain events through API calls in  a custom plugin. When the calls are made and the image is updated I would like to be able to refresh the image but I can't see a way of doing this as only the player can refresh an image in game.

**Comment by LOOHP** [comment]
If you are doing refreshes through API calls, you could just hook into ImageFrame. Otherwise, I believe you can refresh images through the console like this `/if refresh LOOHP:image`.
