### ISSUE TITLE
[Suggestion] Command to Create a New ImageMap as Another Player

### ISSUE THREAD

**Issue by Dizover** [LOOHP/ImageFrame#8]
Is it possible to execute a command in the console to give a map to a certain player? If not, can you please add such a function?

**Comment by LOOHP** [comment]
You can now do that with the `imageframe.get.others` permission and specifying which player at the last argument of the command

**Comment by LOOHP** [comment]
Essentially you want a way to create maps for other players. I'll make sure to consider adding that in the future.

But for now, since you are using a script anyway, perhaps you can give the player permission to create a map, force the player to execute the create command, and then revoke the create map permission afterwards.

**Comment by Dizover** [comment]
Thank you for the offer, I'm not sure that it will be possible to implement it, but I will still wait for the plugin update, thank you for paying attention.

**Comment by Dizover** [comment]
or maybe this command could be `/imageframe get <name> <url> <width> <height> combined <player>`

**Comment by Dizover** [comment]
My friend added this feature to your plugin, but we don't know how to do a pull request, so here [commands.txt](https://github.com/LOOHP/ImageFrame/files/11080848/commands.txt). Can you add this feature? And can you do better if something is wrong? It's working from console with `imageframe create <name> <url> <width> <height> combined <player>`

**Comment by LOOHP** [comment]
I've added function to create maps for other players.
Here is how it works:
`/if create <player>:<name> <url> ...`
Added in 1.7.3.1, feel free to give it a try.

Also answered on discord, you can use that to follow up. Closing this for now.
